version: '3.8'

services:
  frontend:
    image: $DOCKERHUB_USERNAME/velo-frontend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=/
    ports:
      - "8080:8080"
    networks:
      - velo-network

  backend:
    image: $DOCKERHUB_USERNAME/velo-backend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=velo
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=velo
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    depends_on:
      - db
    networks:
      - velo-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=velo
      - MYSQL_USER=velo
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - velo-network

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - velo-network

networks:
  velo-network:
    driver: bridge

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
