version: '3.8'

services:
  frontend:
    build: ./frontend
    image: velo-frontend
    networks:
      - app-network

  backend:
    build: ./backend
    image: velo-backend
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: velo
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: velo
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  caddy:
    image: caddy:2.7-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data:
  caddy-data:
  caddy-config:

networks:
  app-network:
    driver: bridge
