services:
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=velo
      - DB_PASSWORD=velopassword
      - DB_NAME=velo
      - JWT_SECRET=velo_super_secret_key_change_in_production
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    restart: unless-stopped
    # Добавляем проброс порта 3306 наружу
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=velo
      - MYSQL_USER=velo
      - MYSQL_PASSWORD=velopassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
